from gaff import *

if __name__=='__main__':
    a = 'DKGDRLLNIRNEWWYKHFMFQTLWWFDFEESCFGTHVMHANWWLCGNMTWGSKDECPGCCEHHYEACVEYNPKPQSSEFVV'
    b = 'DKQRTYADRFEMCIGMLNIRSEWWYPIYFGTLWWFDFEESCFGTCSSRGNYIAHANWWVCGNMGWGSKDECPGCCEHHKPQCSERFVV'
    
    a = a[:5]
    b = b[:5]
    
    print(align(a, b))